### ISSUE TITLE
Does this only work for shallow rendering?

### ISSUE THREAD

**Issue by JakeDawkins** [rogeliog/jest-serializer-enzyme#8]
I'm trying to work this into an existing project where we use enzyme's `mount` method instead of `shallow` for almost all of our tests.

Whenever trying to create a snapshot using: 

```
const component = mount(<SmallButton />);
expect(component).toMatchSnapshot();
```

I'm getting a `RangeError: Invalid string length` 

Does this method only work for enzyme's `shallow` render method?

**Comment by rogeliog** [comment]
Right, it currently only works with `shallow`, but we should make it work with `mount` as soon as possible :smile:
